name: Build and Test Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-scan-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build API image
        run: docker build -t my-api:1.0.0 -f ./api/Dockerfile .

      - name: Docker Scout Scan API
        uses: docker/scout-action@v1
        with:
          command: cves, recommendations
          image: my-api:1.0.0
          file: ./api/Dockerfile
          only-severities: critical, high
          exit-code: false

  build-and-scan-mongo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build MongoDB image
        run: docker build -t my-mongo:1.0.0 -f ./mongodb/Dockerfile .

      - name: Docker Scout Scan MongoDB
        uses: docker/scout-action@v1
        with:
          command: cves, recommendations
          image: my-mongo:latest
          file: ./mongodb/Dockerfile
          only-severities: critical, high
          exit-code: false
