name: Build and Test Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-scan-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build API image
        run: docker build -t my-api:1.0.0 -f ./api/Dockerfile .

      - name: Docker Scout Scan API
        uses: docker/scout-action@v1
        with:
          command: cves, recommendations
          image: my-api:1.0.0
          file: ./api/Dockerfile
          only-severities: critical, high
          exit-code: false

  build-and-scan-mongo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build MongoDB image
        run: docker build -t my-mongo:1.0.0 -f ./mongodb/Dockerfile .

      - name: Docker Scout Scan MongoDB
        uses: docker/scout-action@v1
        with:
          command: cves, recommendations
          image: my-mongo:1.0.0
          file: ./mongodb/Dockerfile
          only-severities: critical, high
          exit-code: false
  docker-compose:
    needs: [build-and-scan-api, build-and-scan-mongo]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Start Stack
        run: docker compose up -d --build
        env:
          # MongoDB
          MONGODB_INITDB_ROOT_USERNAME: ${{ secrets.MONGODB_INITDB_ROOT_USERNAME }}
          MONGODB_INITDB_ROOT_PASSWORD: ${{ secrets.MONGODB_INITDB_ROOT_PASSWORD }}
          MONGO_URL: ${{ secrets.MONGO_URL }}
          ME_CONFIG_MONGODB_SERVER: ${{ secrets.ME_CONFIG_MONGODB_SERVER }}

          # MySQL
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}

      - name: Afficher les logs en cas d'échec
        if: failure()
        run: |
          echo "=== État des conteneurs ==="
          docker compose ps
          echo "=== Logs de la base MySQL ==="
          docker compose logs db_mysql
          echo "=== Logs de la base MongoDB ==="
          docker compose logs db_mongo
          echo "=== Logs de l'API ==="
          docker compose logs api
          

      - name: Wait for services (Healthcheck)
        run: |
          echo "Waiting for services to be healthy..."
          sleep 40
          docker compose ps
          
      - name: Check Status
        run: |
          if [ $(docker compose ps | grep -c "unhealthy") -gt 0 ]; then
            echo "Erreur : Un service est Unhealthy"
            docker compose logs
            exit 1
          fi
          echo "Bravo : Tout est Healthy !"
    
